sudo: required
services:
  - docker

# We want to make sure tests are passing before running the production build
before_install:
  # Build docker image to use for running tests
  - docker build -t "$DOCKER_ID"/run-client-tests -f ./client/Dockerfile.dev ./client

script:
  # Script for running tests in /client
  - docker run "$DOCKER_ID"/run-client-tests npm run test:ci

# Tests passed, run production build
after_success:
  # Build all Docker images using default Dockerfile config
  - docker build --no-cache -t "$DOCKER_ID"/microservices-client ./client
  - docker build -t "$DOCKER_ID"/microservices-nginx ./nginx
  - docker build -t "$DOCKER_ID"/microservices-server ./server
  - docker build -t "$DOCKER_ID"/microservices-worker ./worker
  # Log in to Docker CLI
  # First execute righthand side - login and enter account name, then use the lefthand as input for password 
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push "$DOCKER_ID"/microservices-client
  - docker push "$DOCKER_ID"/microservices-nginx
  - docker push "$DOCKER_ID"/microservices-server
  - docker push "$DOCKER_ID"/microservices-worker