apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # Only a single mode can access the volumekub
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi