# Same as client-pod config up until spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment

spec:
  # Number of identical pods to be running in this Deployment
  replicas: 1
  # Identifier for pods that will trigger deployment
  selector:
    matchLabels:
      component: web
  # Template for Pods running in this Deployment
  template:
    metadata:
      labels:
        # In this case we only have one tag, other cases we might have some tags that will not trigger deploy
        component: web
    spec:
      containers:
        - name: client
          image: gtntaz/microservices-client
          ports:
            - containerPort: 3000